Disable CGO when using go build
longhorn/longhorn-instance-manager pull request #134
Opened 2022-09-06 09:56 UTC by olljanat

Implements suggestion in https://github.com/longhorn/longhorn/issues/4415#issuecomment-1214885963 and disable CGO here too like it was done in longhorn-manager by https://github.com/longhorn/longhorn-manager/pull/61

2022-09-19 07:59 UTC, innobead requested changes

2022-09-19 07:59 UTC, innobead commented on scripts/build
> +go build --tags netgo -ldflags \
```suggestion
go build -tags netgo -ldflags \
```

2022-09-19 13:10 UTC, olljanat commented on scripts/build
> +go build --tags netgo -ldflags \
Good catch. Fixed.

2022-09-26 04:25 UTC, olljanat commented
@innobead typo fixed, please check again.

2022-11-11 04:22 UTC, olljanat commented
PR is still valid

2022-11-14 03:02 UTC, innobead commented
Because the instance manager has the proxy capability and it is actually the core of the data plane, we need this as well instead of longhorn-engine only. (probably we will reach out to the service in DNS from the instance manager)

2022-11-14 03:03 UTC, innobead approved these changes
Merge after QA verification. 

cc @longhorn/qa @roger-ryao

2022-11-15 02:04 UTC, roger-ryao commented
> Merge after QA verification.
> 
> cc @longhorn/qa @roger-ryao

Hi @innobead 
- [core test report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2448/)
- [regression test report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2447/)
- [The failed cases re-run report](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2457/)

The test PASS, we could merge longhorn-instance-manager PR
cc @longhorn/qa

2022-11-15 02:21 UTC, merged