feat: talos support
longhorn/longhorn-instance-manager pull request #273
Opened 2023-08-03 06:40 UTC by c3y1huang

https://github.com/longhorn/longhorn/issues/3161

2023-08-28 01:35 UTC, c3y1huang commented on go.mod
> +replace github.com/longhorn/go-common-libs => github.com/c3y1huang/go-common-libs v0.0.0-20230818102433-680b5db81371
TODO: update after https://github.com/longhorn/go-common-libs/pull/1

2023-08-28 01:35 UTC, c3y1huang commented on go.mod
> +replace github.com/longhorn/longhorn-engine => github.com/c3y1huang/longhorn-engine v1.4.0-rc1.0.20230818103126-3ba57dbd5d39
TODO: update after https://github.com/longhorn/longhorn-engine/pull/919

2023-12-20 09:27 UTC, innobead approved these changes
Just wait for longhorn-engine PR merge first.

2023-12-21 12:47 UTC, innobead requested changes
Please update the engine dep.

2023-12-22 03:38 UTC, innobead approved these changes

2023-12-22 03:39 UTC, merged