build: reduce iamge size by removing unused packages
longhorn/longhorn-instance-manager pull request #311
Opened 2023-11-16 07:00 UTC by ChanYiLin

ref: https://github.com/longhorn/longhorn/issues/5911

2023-11-16 07:02 UTC, ChanYiLin commented
> This pull request is now in conflicts. Could you fix it @ChanYiLin? 🙏

conflicts resolved

2023-11-16 07:03 UTC, ChanYiLin commented
e2e tests: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5257/

2023-11-16 08:05 UTC, derekbit commented on package/Dockerfile
> +    iputils iproute2 qemu-tools e2fsprogs util-linux-systemd python3 && \
Is python3 necessary?

2023-11-17 04:16 UTC, ChanYiLin commented on package/Dockerfile
> +    iputils iproute2 qemu-tools e2fsprogs util-linux-systemd python3 && \
Removed, thanks!

2023-11-17 04:16 UTC, ChanYiLin commented
> In general, LGTM.
> 
> Just have the same question as Derek, python3 runtime should not required.

Hi @innobead , removed, thanks!

2023-11-17 04:37 UTC, derekbit approved these changes

2023-11-17 06:53 UTC, innobead requested changes
Do we need the following repos in the image?

```bash
    zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:libraries:c_c++/15.4/devel:libraries:c_c++.repo && \
    zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:languages:python:Factory/15.4/devel:languages:python:Factory.repo && \
    zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:languages:python:backports/SLE_15/devel:languages:python:backports.repo && \
```

2023-11-17 06:53 UTC, innobead commented on package/Dockerfile
> +RUN zypper -n install nfs-client nfs4-acl-tools cifs-utils libaio1 sg3_utils \
`libaio1` will be used at runtime?

2023-11-17 07:01 UTC, ChanYiLin commented
> Do we need the following repos in the image?
> 
> ```shell
>     zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:libraries:c_c++/15.4/devel:libraries:c_c++.repo && \
>     zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:languages:python:Factory/15.4/devel:languages:python:Factory.repo && \
>     zypper -n addrepo --refresh https://download.opensuse.org/repositories/devel:languages:python:backports/SLE_15/devel:languages:python:backports.repo && \
> ```


These are added when introducing spdk, don't know if these are needed in the runtime, may meed to ask @derekbit 
https://github.com/longhorn/longhorn-instance-manager/commit/0225d0454aeba17ea2edfa2b34d900e0dbf34e3a

2023-11-17 07:03 UTC, ChanYiLin commented
oh wait those are just adding repo
I think we can remove them since we are not installing these package in runtime

2023-11-17 08:42 UTC, ChanYiLin commented on package/Dockerfile
> +RUN zypper -n install nfs-client nfs4-acl-tools cifs-utils libaio1 sg3_utils \
removed

2023-11-17 08:44 UTC, innobead approved these changes

2023-11-17 08:45 UTC, derekbit commented
Don’t merge. The spdk that cannot be started after applying the PR.

取得 iOS 版 Outlook<https://aka.ms/o0ukef>
________________________________
寄件者: David Ko ***@***.***>
寄件日期: Friday, November 17, 2023 4:44:15 PM
收件者: longhorn/longhorn-instance-manager ***@***.***>
副本: Derek Su ***@***.***>; Mention ***@***.***>
主旨: Re: [longhorn/longhorn-instance-manager] build: reduce iamge size by removing unused packages (PR #311)


@innobead approved this pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/longhorn/longhorn-instance-manager/pull/311#pullrequestreview-1736322952>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AC7SNALWY4KWGUV4A4WYIYDYE4PV7AVCNFSM6AAAAAA7NU23M2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMZWGMZDEOJVGI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-11-17 11:51 UTC, derekbit commented
Ref 

http://github.com/derekbit/longhorn-instance-manager/commit/55cb84a77c080a66d01d146aeab4b565e0b7098d

cc @ChanYiLin

2023-11-21 03:11 UTC, ChanYiLin commented
Hi @derekbit @innobead 
I have tested the PR
- amd64 coretest
- arm64 coretest
- install longhorn and try spdk volume function (attach to pods)

Do we still have any concerns I missed?

2023-11-22 10:32 UTC, innobead approved these changes
LGTM.

However, we need to review if we still need the following dependenceies at the runtime image, because it seems installing unnecessary dependdencies for building SPDK artificats, even though some runtime libs we do need. 

```bash
# Install SPDK dependencies
COPY --from=builder /usr/src/spdk/scripts /spdk/
RUN if [ "${ARCH}" == "amd64" ]; then \
        sh /spdk/pkgdep.sh; \
        rm -rf /tmp/spdk; \
    fi
```

2023-11-22 12:01 UTC, derekbit commented
@ChanYiLin 
Can you replace `rm -rf /tmp/spdk; \` with `rm -rf /spdk; \`? Thank you.

2023-11-22 12:04 UTC, derekbit commented
> LGTM.
> 
> However, we need to review if we still need the following dependencies at the runtime image, because it seems to install unnecessary dependencies for building SPDK artifacts, even though we need some runtime libs.
> 
> ```shell
> # Install SPDK dependencies
> COPY --from=builder /usr/src/spdk/scripts /spdk/
> RUN if [ "${ARCH}" == "amd64" ]; then \
>         sh /spdk/pkgdep.sh; \
>         rm -rf /tmp/spdk; \
>     fi
> ```

After a quick check, pkgdeps.sh installs the minimal dependencies because we don't enable unnecessary options.
However, the four tools are not required.
https://github.com/spdk/spdk/blob/master/scripts/pkgdep/sles.sh#L14

2023-11-23 03:42 UTC, ChanYiLin commented
> @ChanYiLin Can you replace `rm -rf /tmp/spdk; \` with `rm -rf /spdk; \`? Thank you.

Hi @derekbit fixed, thanks!

2023-11-23 04:43 UTC, derekbit approved these changes

2023-11-23 05:45 UTC, innobead approved these changes

2023-11-24 01:16 UTC, derekbit approved these changes

2023-11-24 01:39 UTC, merged

2023-11-24 01:42 UTC, innobead commented
Not sure why can't rebase and then merge the PR. IIRC, there were several times when merging your PRs. @ChanYiLin , probably need to check how to resolve this next time.

2023-11-24 03:04 UTC, derekbit commented
> Not sure why can't rebase and then merge the PR. IIRC, there were several times when merging your PRs. @ChanYiLin , probably need to check how to resolve this next time.

https://github.com/orgs/community/discussions/27521

2023-11-27 04:13 UTC, ChanYiLin commented
@mergify backport v1.5.x